### PR TITLE
feat(help): add auto help catch if no args found

### PR DESCRIPTION
**Pull request by awitherow**

### CODE REVIEW

**Comment by awitherow** [comment]
This is really not clear to me how to do it, but it is not the (*) functionality.

Have asked at https://github.com/tj/commander.js/issues/623

**Comment by DanielMSchmidt** [comment]
Maybe it has to added last so it is like a fall-through? Just an idea, no evidence unfortunately :(

**Comment by awitherow** [comment]
I've taken this advice and updated the commit. Haven't had time to try it out yet tho! https://github.com/tj/commander.js/issues/623#issuecomment-297232782

**Comment by awitherow** [comment]
@DanielMSchmidt isn't working for me, you got it working potentially on your machine?

**Comment by awitherow** [comment]
@DanielMSchmidt can't get it working, is it working for you?

**Pull request closed without merging**
